### ISSUE TITLE
How to resume my project from latest checkpoint

### ISSUE THREAD

**Issue by robotzzh** [guangkun0818/speech2text#18]
My project was training for 9 hours when it encountered an OOM (Out of Memory) error in CUDA. I want to resume it from the latest checkpoint. How can I do that?

**Comment by guangkun0818** [comment]
`callbacks:
  model_chkpt_config:
    monitor: "wer"
    mode: "min"
    save_top_k: 10
  frontend_save: false
  global_cmvn:
    apply: false
    pre_compute_cmvn: null

finetune:
  base_model: null 
resume: null`
Set the path of saved chkpt you intend to resume to `resume` in your training config as above.

**Comment by guangkun0818** [comment]
> 	My project was training for 9 hours when it encountered an OOM (Out of Memory) error in CUDA. I want to resume it from the latest checkpoint. How can I do that?

```yaml
callbacks:
  model_chkpt_config:
    monitor: "wer"
    mode: "min"
    save_top_k: 10
  frontend_save: false
  global_cmvn:
    apply: false
    pre_compute_cmvn: null

finetune:
  base_model: null 
resume: null
```

Set the path of saved chkpt you intend to resume to `resume` in your training config as above.
